# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Vlax Romani spellchecker"
rmy = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Vlax Romani, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
rmy = "TRANSLATE: A spellchecker for Vlax Romani, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.rmy"

[windows]
system_product_code = "{2B76B81B-C81E-4F49-8743-505CF542A294}_is1"
legacy_product_codes = [
    { value = "999163E6-A967-419B-9649-005C6EC9A49B", kind = "nsis" },
    { value = "88B79EE3-8CD5-4FD4-B4AC-B45DFC143F52", kind = "nsis" }
]

[package.speller]
name = "Vlax Romani"
version = "0.1.1"

[package.grammar]
name = "Vlax Romani"
version = "0.1.0"

[package.tts-text-proc]
name = "Vlax Romani"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
