template = "https://github.com/giellalt/template-lang-und"
rev_id = 259
template_sha = "dbafdbc00bdeb17f80ec54b2fd5d6ae330f25f51"

[replacements]
__GLOTTOLOG_ID__ = "vlax1238"
__REPO__ = "lang-rmy"
__UND2C__ = "rmy"
__UNDEFINED__ = "Vlax Romani"
__UND__ = "rmy"
