template = "https://github.com/giellalt/template-lang-und"
rev_id = 252
template_sha = "00bea80a90b92870230cbd76cf7ed0fece87f2c0"

[replacements]
__GLOTTOLOG_ID__ = "vlax1238"
__REPO__ = "lang-rmy"
__UND2C__ = "rmy"
__UNDEFINED__ = "Vlax Romani"
__UND__ = "rmy"
